[[language]]
name = "python"
language-servers = [
  "ruff",
  "ty",
  "pyright"
]

[[language]]
name = "rust"

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.ruff.config.settings]
logLevel = "debug"
logFile = "~/.cache/helix/ruff.log"

[language-server.ty]
command = "/Users/dhruv/work/astral/ruff/target/debug/ty"
args = ["server"]

[language-server.ty.config.settings]
logLevel = "debug"
logFile = "~/.cache/helix/ty.log"

[language-server.ruff-lsp]
command = "ruff-lsp"

[language-server.rust-analyzer.config]
cargo = { features = "all" }
checkOnSave = { command = "clippy" }
