[[language]]
name = "python"
language-servers = ["ruff", "pyright"]

[[language]]
name = "rust"

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.ruff]
command = "/Users/dhruv/work/astral/ruff/target/debug/ruff"
args = ["server"]
environment = { "RUFF_TRACE" = "messages" }

[language-server.ruff.config.settings]
logLevel = "debug"
logFile = "/Users/dhruv/.cache/helix/ruff.log"

[language-server.ruff-lsp]
command = "ruff-lsp"

[language-server.rust-analyzer.config]
cargo = { features = "all" }
checkOnSave = { command = "clippy" }
