[[language]]
name = "python"
language-servers = ["pyright", "ruff-lsp"]

[[language]]
name = "rust"

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.ruff]
command = "ruff"
args = ["server", "--preview"]

[language-server.ruff-lsp]
command = "ruff-lsp"

[language-server.rust-analyzer]
config = { cargo = { features = "all" }, checkOnSave = { command = "clippy" } }
