os: macos
language: bash

git:
  clone: false

cache:
  directories:
    - $HOME/Library/Caches/Homebrew
    - /usr/local/Homebrew

before_cache:
  - if [ "${TRAVIS_OS_NAME}" -eq "osx" ]; then brew cleanup; fi
# Credit https://discourse.brew.sh/t/best-practice-for-homebrew-on-travis-brew-update-is-5min-to-build-time/5215/9
# Cache only .git files under "/usr/local/Homebrew" so "brew update" does not take 5min every build
  - if [ "${TRAVIS_OS_NAME}" -eq "osx" ]; then find /usr/local/Homebrew \! -regex ".+\.git.+" -delete; fi

before_script:
  - curl -o bootstrap.sh https://raw.githubusercontent.com/dhruvmanila/dotfiles/master/bootstrap
  - echo -e "y\ny\n" > response.txt

script:
  - bash bootstrap.sh < response.txt
