os: osx
language: shell

git:
  clone: false

cache:
  timeout: 600
  ccache: true
  directories:
    - ${HOME}/Library/Caches/Homebrew
    - /usr/local/Homebrew

before_cache:
  - brew cleanup
    # Credit https://discourse.brew.sh/t/best-practice-for-homebrew-on-travis-brew-update-is-5min-to-build-time/5215/9
    # Cache only .git files under "/usr/local/Homebrew" so "brew update" does not take 5min every build
    # Find workaround on macOS due to https://superuser.com/a/1459901/151744
  - cd "/usr/local/Homebrew" && find . \! -regex ".+\.git.+" -delete

before_script:
  - curl -o bootstrap.sh https://raw.githubusercontent.com/dhruvmanila/dotfiles/master/bootstrap
  - echo -e "y\ny\n" > response.txt

script:
  - bash bootstrap.sh < response.txt
