os: osx
language: shell

git:
  clone: false

cache:
  directories:
    - ${HOME}/Library/Caches/Homebrew

before_cache:
  - brew cleanup

before_script:
  - curl -o bootstrap.sh https://raw.githubusercontent.com/dhruvmanila/dotfiles/master/bootstrap
  - echo -e "y\ny\n" > response.txt

script:
  - bash bootstrap.sh < response.txt
