tap "clementtsang/bottom"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "mongodb/brew"
tap "romkatv/gitstatus"
# Static checker for GitHub Actions workflow files
brew "actionlint"
# Tool for generating GNU Standards-compliant Makefiles
brew "automake"
# Command-line interface for SQLite
brew "sqlite"
# General-purpose data compression with high compression ratio
brew "xz"
# Microsoft Azure CLI 2.0
brew "azure-cli"
# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# Programmable completion for Bash 4.2+
brew "bash-completion@2"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Garbage collector for C and C++
brew "bdw-gc"
# Generate compilation database for clang tooling
brew "bear"
# GNU internationalization (i18n) and localization (l10n) library
brew "gettext"
# Manage compile and link flags for libraries
brew "pkg-config"
# Tool Command Language
brew "tcl-tk"
# Vector graphics library with cross-device output support
brew "cairo"
# Ultralightweight JSON parser in ANSI C
brew "cjson"
# Cross-platform make
brew "cmake"
# Console Matrix
brew "cmatrix"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Tool to perform numerical, textual & statistical operations
brew "datamash"
# DuckDuckGo from the terminal
brew "ddgr"
# Tool for exploring each layer in a docker image
brew "dive"
# Generate documentation for several programming languages
brew "doxygen"
# Maintain consistent coding style between multiple editors
brew "editorconfig"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Generic library support script
brew "libtool"
# Validating, recursive, caching DNS resolver
brew "unbound"
# OpenType text shaping engine
brew "harfbuzz"
# Extremely Fast Compression algorithm
brew "lz4"
# Secure Reliable Transport
brew "srt"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# Collection of GNU find, xargs, and locate
brew "findutils"
# Command-line fuzzy finder written in Go
brew "fzf"
# GNU debugger
brew "gdb"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Syntax-highlighting pager for git and diff output
brew "git-delta"
# GNU Pretty Good Privacy (PGP) package
brew "gnupg"
# Smarter Dockerfile linter to validate best practices
brew "hadolint"
# CLI email client written in Rust
brew "himalaya"
# Improved top (interactive process viewer)
brew "htop"
# Configurable static site generator
brew "hugo"
# Command-line benchmarking tool
brew "hyperfine"
# Lightweight and flexible command-line JSON processor
brew "jq"
# User-friendly front-end to ssh-agent(1)
brew "keychain"
# Pager program similar to more
brew "less"
# LLVM's OpenMP runtime library
brew "libomp"
# Framework for layout and rendering of i18n text
brew "pango"
# Next-gen compiler infrastructure
brew "llvm"
# Curses-based tool for viewing and analyzing log files
brew "lnav"
# Language Server for the Lua language
brew "lua-language-server"
# Package manager for the Lua programming language
brew "luarocks"
# Utility for directing compilation
brew "make"
# Mac App Store command-line interface
brew "mas"
# MongoDB CLI enables you to manage your MongoDB in the Cloud
brew "mongocli"
# Collection of tools that nobody wrote when UNIX was young
brew "moreutils"
# Open source relational database management system
brew "mysql"
# HTTP(S) server and reverse proxy, and IMAP/POP3 proxy server
brew "nginx"
# Small build system for use with gyp or CMake
brew "ninja"
# Platform built on V8 to build network applications
brew "node"
# Cryptography and SSL/TLS Toolkit
brew "openssl@3"
# Tool for creating identical machine images for multiple platforms
brew "packer"
# Paragraph reflow for email
brew "par"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Password manager
brew "pass"
# Pinentry for GPG on Mac
brew "pinentry-mac"
# Object-relational database system
brew "postgresql"
# Object-relational database system
brew "postgresql@13"
# Coreutils progress viewer
brew "progress"
# Persistent key-value database, with built-in net interface
brew "redis"
# Perl-powered file rename script with many helpful built-ins
brew "rename"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Powerful, clean, object-oriented scripting language
brew "ruby"
# Safe, concurrent, practical language
brew "rust"
# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"
# Autoformat shell script source code
brew "shfmt"
# Cross-shell prompt for astronauts
brew "starship"
# Opinionated Lua code formatter
brew "stylua"
# Very fast implementation of tldr in Rust
brew "tealdeer"
# Tool to build, change, and version infrastructure
brew "terraform"
# Terminal multiplexer
brew "tmux"
# CLI tool that moves files or folder to the trash
brew "trash"
# Maintained ctags implementation
brew "universal-ctags"
# Bash completion for Vagrant
brew "vagrant-completion"
# Vi 'workalike' with many additional features
brew "vim"
# Process YAML documents from the CLI
brew "yq"
# Fork of youtube-dl with additional features and fixes
brew "yt-dlp"
# UNIX shell (command interpreter)
brew "zsh"
# Additional completion definitions for zsh
brew "zsh-completions"
# A cross-platform graphical process/system monitor with a customizable interface and a multitude of features.
brew "clementtsang/bottom/bottom"
# Everything you need to get started with Heroku
brew "heroku/brew/heroku"
# High-performance, schema-free, document-oriented database
brew "mongodb/brew/mongodb-community"
# Git status for Bash/Zsh prompt
brew "romkatv/gitstatus/gitstatus"
# Web browser focusing on privacy
cask "brave-browser"
# Browser for SQLite databases
cask "db-browser-for-sqlite"
# Voice and text chat software
cask "discord"
# App to build and share containerized applications and microservices
cask "docker"
# Draw.io is free online diagram software
cask "drawio"
cask "font-fira-code"
# Typeface made for developers
cask "font-jetbrains-mono"
# Desktop automation application
cask "hammerspoon"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# Keyboard customizer
cask "karabiner-elements"
# GPU-based terminal emulator
cask "kitty"
# Provides updates to various Microsoft products
cask "microsoft-auto-update"
# Email client
cask "microsoft-outlook"
# Meet, chat, call, and collaborate in just one place
cask "microsoft-teams"
# Explore and manipulate your MongoDB data
cask "mongodb-compass"
# Tool to control external monitor brightness & volume
cask "monitorcontrol"
# Media player based on MPlayer and mplayer2
cask "mpv"
# App to write, plan, collaborate, and get organized
cask "notion"
# Administration and development platform for PostgreSQL
cask "pgadmin4"
# Collaboration platform for API development
cask "postman"
# Peer to peer Bitorrent client
cask "qbittorrent"
# Move and resize windows using keyboard shortcuts or snap areas
cask "rectangle"
# Team communication and collaboration software
cask "slack"
# Development environment
cask "vagrant"
# Virtualizer for x86 hardware
cask "virtualbox"
# Open-source code editor
cask "visual-studio-code"
# Multimedia player
cask "vlc"
# Desktop client for WhatsApp
cask "whatsapp"
mas "Azure VPN Client", id: 1553936137
mas "Hotspot Shield", id: 771076721
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Speedtest", id: 1153157709
mas "The Unarchiver", id: 425424353
mas "Vimari", id: 1480933944
