#!/usr/bin/env bash

# This bash completions script was generated by
# completely (https://github.com/dannyben/completely)
# Modifying it manually is not recommended
_dotbot_completions() {
  local cur=${COMP_WORDS[COMP_CWORD]}
  local comp_line="${COMP_WORDS[@]:1}"

  case "$comp_line" in
    'upgrade'*) COMPREPLY=($(compgen -W "--help --ref -h -r all brew cargo mac neovim nnn npm plugins python" -- "$cur")) ;;
    'shell'*) COMPREPLY=($(compgen -W "--help -h" -- "$cur")) ;;
    'setup'*) COMPREPLY=($(compgen -W "--help -h" -- "$cur")) ;;
    'link'*) COMPREPLY=($(compgen -W "--force --help -f -h" -- "$cur")) ;;
    'sync'*) COMPREPLY=($(compgen -W "--brew --cargo --help --node --python -b -c -h -n -p" -- "$cur")) ;;
    ''*) COMPREPLY=($(compgen -W "--help --version -h -v link setup shell sync upgrade" -- "$cur")) ;;
  esac
}

complete -F _dotbot_completions dotbot
