#!/usr/bin/env bash

alias python="python3"
alias g="git"
alias d="docker"
alias dc="docker-compose"
alias yt="youtube-dl"

# nnn (to reset less)
alias nnn='LESS=-R nnn'

# Neovim
alias v="nvim"
alias vi="nvim"
alias vm='nvim -nu ${HOME}/dotfiles/config/nvim/minimal.lua'

# Neovim development
alias dv='cd ${HOME}/contributing/neovim && VIMRUNTIME=runtime ./build/bin/nvim && cd -'
alias dvr='cd ${HOME}/contributing/neovim && VIMRUNTIME=${HOME}/neovim/share/nvim/runtime ./build/bin/nvim && cd -'

alias vim-startuptime='vim-startuptime | head -n 30'
alias nvim-startuptime='\vim-startuptime -vimpath nvim | head -n30'

# Always show size in human readable format
alias du='du -h'
alias usage='du -d 1'

# Default to using Finder for trash.
alias trash='trash -F'

# I don't know any other way to find out if I'm using the kitty terminal or not.
if [[ -n "$KITTY_PID" ]]; then
  alias ssh='kitty +kitten ssh'
fi

# Fix ownership in /usr/local/ directories
alias fixlocal='cd /usr/local && sudo chown -R $(whoami) bin etc include lib sbin share var Frameworks'

# Opens the editor with vertical splits, each containing the output from the
# below substitutions.
#
# 1. Names and values of shell variables
# 2. Shell option settings (set/unset)
# 3. Readline variables
# 4. Readline keybindings
alias options='nvim -O <(set -o) <(shopt) <(bind -v) <(bind -p)'

# Easier navigation
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias -- -="cd -" # cd to the previous directory

# Reload the shell (i.e. invoke as a login shell)
alias reload='exec ${SHELL} -l'

# Print each PATH entry on a separate line
alias path='echo -e ${PATH//:/\\n}'

# Show/hide hidden files in Finder
alias showhidden="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
alias hidehidden="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"

# Hide/show all desktop icons
alias show="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"
alias hide="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"

# Recursively delete `.DS_Store` files
alias cleanup="find . -type f -name '*.DS_Store' -ls -delete"

# Empty the Trash on all mounted volumes and the main HDD.
# Also, clear Apple’s System Logs to improve shell startup speed.
# Finally, clear download history from quarantine. https://mths.be/bum
alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl; sqlite3 ~/Library/Preferences/com.apple.LaunchServices.QuarantineEventsV* 'delete from LSQuarantineEvent'"

# Get macOS Software Updates
alias update='sudo softwareupdate --install --all'

# Detect which `ls` flavor is in use
if ls --color > /dev/null 2>&1; then # GNU `ls`
  alias ls='ls --color=auto -h -F'
else # macOS `ls`
  alias ls='ls -G -h -F'
fi

# List all files colorized in long format
alias l='ls -l'

# List all files colorized in long format, excluding . and ..
alias la='ls -lA'

# List only directories
alias ld='ls -l | grep -Ei --color=always " [a-z0-9.-]+/$"'

# List all the directories
alias lda='ls -lA | grep -Ei --color=always " [a-z0-9.-]+/$"'
