# https://github.com/Koihik/LuaFormatter/blob/master/docs/Style-Config.md
column_limit: 100
indent_width: 2
use_tab: false
continuation_indent_width: 2
keep_simple_control_block_one_line: true
keep_simple_function_one_line: true
break_after_functioncall_lp: true
break_before_functioncall_rp: true
break_after_functiondef_lp: true
break_before_functiondef_rp: true
break_after_table_lb: true
break_before_table_rb: true
align_args: false
align_parameter: false
chop_down_parameter: false
chop_down_kv_table: true
extra_sep_at_table_end: true
break_after_operator: false
single_quote_to_double_quote: true
double_quote_to_single_quote: false
