#!/usr/bin/env bash

# Just for testing this script
# source ./utils

DOTFILES_DIRECTORY=${HOME}/dotfiles

run_brew() {
    # Check for Homebrew
    if type_exists 'brew'; then

        export HOMEBREW_NO_AUTO_UPDATE=1
        touch homebrew.log
        
        e_header "Updating Homebrew..."

        BREW_PREFIX=$(brew --prefix)

        # Use the latest version of Homebrew
        brew update >> homebrew.log 2>&1
        e_success "Done"

        e_header "Updating any existing Homebrew formulae..."
        # Upgrade any already-installed formulae
        brew upgrade >> homebrew.log 2>&1
        e_success "Done"

        e_header "Checking status of desired Homebrew formulae..."
        local -a missing_formulae

        if [ "${BASH_VERSINFO[0]}" -ge 4 ]; then
            readarray -t desired_formulae < "${DOTFILES_DIRECTORY}/lib/packages/brew_formulae.txt"
        else
            local -a desired_formulae
            while IFS= read -r line; do
                desired_formulae+=("$line")
            done < "${DOTFILES_DIRECTORY}/lib/packages/brew_formulae.txt"
        fi

        for formula in "${desired_formulae[@]}"; do
            if ! formula_exists "${formula}"; then
                missing_formulae=("${missing_formulae[@]}" "${formula}")
            fi
        done


        if [[ "${missing_formulae[*]}" ]]; then

            e_header "Installing missing Homebrew formulae..."
            # Install all missing formulae
            for formula in "${missing_formulae[@]}"; do
                e_header "Installing ${formula}..."
                brew install "$formula" >> homebrew.log 2>&1
                if formula_exists "$formula" &> /dev/null; then
                    e_success "Successfully installed ${formula}"
                else
                    e_error "Failed to install ${formula}"
                fi
            done

        fi

        # Remove outdated versions from the Cellar
        e_header "Cleaning up..."
        if brew cleanup --debug >> homebrew.log 2>&1; then
            e_success "Done"
        else 
            e_error "Failure occured at cleanup stage, debugging..."
            brew cleanup --debug >> homebrew.log 2>&1
            e_error "Showing the homebrew log, continuing..."
            cat homebrew.log
        fi

        # Switch to using brew-installed bash as default shell
        if ! grep -F -q "${BREW_PREFIX}/bin/bash" /etc/shells; then
            e_header "Switching to brew-installed bash as default shell..."
            echo "${BREW_PREFIX}/bin/bash" | sudo tee -a /etc/shells;
            sudo chsh -s "${BREW_PREFIX}/bin/bash";
            e_success "Done"
        fi;

        if [ -e homebrew.log ]; then
            rm -rf homebrew.log
        fi

    else
        printf "\n"
        e_error "Error: Homebrew not found"
        printf "Aborting...\n"
        exit 1
    fi

    unset BREW_PREFIX formula
}

