#!/usr/bin/env bash

DOTFILES_DIRECTORY="${HOME}/dotfiles"

function run_brew() {

    # Check for Homebrew
    if type_exists "brew"; then
        BREW_PREFIX=$(brew --prefix)
        export HOMEBREW_NO_AUTO_UPDATE=1

        # Only run the commands if we are not in CI
        if [[ -z "$CI" ]]; then
            header "Updating Homebrew..."
            brew update
            header "Updating any existing Homebrew formulae..."
            brew upgrade
        fi

        header "Checking status of desired Homebrew formulae..."
        local -a missing_formulae
        local -a brew_list

        # Collect all the installed formulae
        while IFS= read -r line; do
            brew_list+=("$line");
        done < <(brew list --formula)

        # Check whether the desired formulae exists, if not then collect
        # them in a list to be installed later
        while IFS= read -r formula; do
            if contains_element "${formula}" "${brew_list[@]}"; then
                success "${formula} already installed"
            else
                missing_formulae+=("${formula}")
                warning "Missing formula: ${formula}"
            fi
        done < "${DOTFILES_DIRECTORY}/lib/packages/brew_formulae.txt"

        # Install all the missing formulae
        if [[ "${missing_formulae[*]}" ]]; then
            header "Installing missing Homebrew formulae..."
            for formula in "${missing_formulae[@]}"; do
                header "Installing ${formula}..."
                brew install "$formula"
                if formula_exists "$formula"; then
                    success "Successfully installed ${formula}"
                else
                    error "Failed to install ${formula}"
                fi
            done
        fi

        header "Cleaning up..."
        brew cleanup

        if ! grep -F -q "${BREW_PREFIX}/bin/bash" /etc/shells; then
            header "Switching to brew-installed bash as default shell..."
            echo "${BREW_PREFIX}/bin/bash" | sudo tee -a /etc/shells;
            sudo chsh -s "${BREW_PREFIX}/bin/bash";
            success "Done"
        fi;

    else
        printf "\n"
        error "Error: Homebrew not found"
        printf "Aborting...\n"
        exit 1
    fi

    unset BREW_PREFIX formula
}
