#!/usr/bin/env bash

# Just for testing this script
# source ./utils

DOTFILES_DIRECTORY=${HOME}/dotfiles

run_brew() {
    local -i returncode=0

    # Check for Homebrew
    if type_exists 'brew'; then

        BREW_PREFIX=$(brew --prefix)
        export HOMEBREW_NO_AUTO_UPDATE=1
        
        e_header "Updating Homebrew..."
        # Use the latest version of Homebrew
        brew update &> /dev/null || returncode=1
        e_success "Done"

        e_header "Updating any existing Homebrew formulae..."
        # Upgrade any already-installed formulae
        brew upgrade &> /dev/null || returncode=1
        e_success "Done"

        e_header "Checking status of desired Homebrew formulae..."
        local -a missing_formulae
        local -a brew_list
        brew_list=($(brew list))

        while IFS= read -r formula; do
            if contains_element "${formula}" "${brew_list[@]}"; then
                e_success "${formula} already installed"
            else
                missing_formulae+=("${formula}")
                e_warning "Missing formula: ${formula}"
            fi
        done < "${DOTFILES_DIRECTORY}/lib/packages/brew_formulae.txt"

        if [[ "${missing_formulae[*]}" ]]; then

            e_header "Installing missing Homebrew formulae..."
            for formula in "${missing_formulae[@]}"; do
                e_header "Installing ${formula}..."
                brew install "$formula" &> /dev/null || returncode=1
                if formula_exists "$formula" &> /dev/null; then
                    e_success "Successfully installed ${formula}"
                else
                    e_error "Failed to install ${formula}"
                fi
            done

        fi

        # Remove outdated versions from the Cellar
        e_header "Cleaning up..."
        if brew cleanup; then
            e_success "Done"
        else 
            e_error "Failure occured at cleanup stage, continuing..."
        fi

        # Switch to using brew-installed bash as default shell
        if ! grep -F -q "${BREW_PREFIX}/bin/bash" /etc/shells; then
            e_header "Switching to brew-installed bash as default shell..."
            echo "${BREW_PREFIX}/bin/bash" | sudo tee -a /etc/shells;
            sudo chsh -s "${BREW_PREFIX}/bin/bash";
            e_success "Done"
        fi;

    else
        printf "\n"
        e_error "Error: Homebrew not found"
        printf "Aborting...\n"
        exit 1
    fi

    unset BREW_PREFIX formula
    return ${returncode}
}

