#!/usr/bin/env bash

alias python="python3"
alias g="git"
alias p="pyenv"
alias dc="docker-compose"

# nnn (to reset less)
alias nnn='LESS=-R nnn'

# Brew installed neovim (HEAD version)
alias v="nvim"
alias vi="nvim"

# Neovim development
alias dv='cd ${HOME}/contributing/neovim && VIMRUNTIME=runtime ./build/bin/nvim'
alias dvr='cd ${HOME}/contributing/neovim && VIMRUNTIME=${HOME}/neovim/share/nvim/runtime ./build/bin/nvim'

# Fix ownership in /usr/local/ directories
alias fixlocal='cd /usr/local && sudo chown -R $(whoami) bin etc include lib sbin share var Frameworks'

alias yt="youtube-dl"

# Easy activate/deactivate virtual environments ('p' prefix for Python)
# alias pva='pyenv activate'
# alias pvd='pyenv deactivate'

# Easier navigation
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias -- -="cd -"  # cd to the previous directory

# Reload the shell (i.e. invoke as a login shell)
alias reload='exec ${SHELL} -l'

# Print each PATH entry on a separate line
alias path='echo -e ${PATH//:/\\n}'

# URL-encode strings
alias urlencode='python -c "import sys, urllib as ul; print ul.quote_plus(sys.argv[1]);"'

# Show/hide hidden files in Finder
alias showhidden="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
alias hidehidden="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"

# Hide/show all desktop icons
alias show="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"
alias hide="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"

# Recursively delete `.DS_Store` files
alias cleanup="find . -type f -name '*.DS_Store' -ls -delete"

# Empty the Trash on all mounted volumes and the main HDD.
# Also, clear Apple’s System Logs to improve shell startup speed.
# Finally, clear download history from quarantine. https://mths.be/bum
alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl; sqlite3 ~/Library/Preferences/com.apple.LaunchServices.QuarantineEventsV* 'delete from LSQuarantineEvent'"

# Get macOS Software Updates, and update installed Ruby gems, Homebrew, npm, and their installed packages
alias update='sudo softwareupdate -i -a; brew update; brew upgrade; brew cleanup'

# Detect which `ls` flavor is in use
if ls --color > /dev/null 2>&1; then # GNU `ls`
  colorflag="--color"
else # macOS `ls`
  colorflag="-G"
fi

# List all files colorized in long format
alias l="ls -lhF ${colorflag}"

# List all files colorized in long format, excluding . and ..
alias la="ls -lhAF ${colorflag}"

# List only directories
alias ld="ls -lhF ${colorflag} | grep -Ei --color=always ' [a-z0-9.-]+/$'"

# List all the directories
alias lda="ls -lhAF ${colorflag} | grep -Ei --color=always ' [a-z0-9.-]+/$'"

# Always use color output for `ls`
alias ls="ls ${colorflag} -h"

unset colorflag
