#!/usr/bin/env bash
# vim: set ft=sh:

# For docker-compose (internetarchive/openlibrary)
export COMPOSE_FILE="docker-compose.yml:docker-compose.override.yml:docker-compose.infogami-local.yml"

# Disale default conda base getting activated by default
export CONDA_AUTO_ACTIVATE_BASE=false

# Disable pyenv virtualenv prompt
export PYENV_VIRTUALENV_DISABLE_PROMPT=1

# Hide the “default interactive shell is now zsh” warning on macOS.
export BASH_SILENCE_DEPRECATION_WARNING=1

# Make vim the default editor.
export EDITOR='nvim'
export VISUAL="$EDITOR"

# Increase Bash history size.
export HISTSIZE='32768'
export HISTFILESIZE="${HISTSIZE}"
# Omit duplicates and commands that begin with a space from history.
export HISTCONTROL='ignoreboth'

# Prefer US English and use UTF-8.
export LANG='en_US.UTF-8'
export LC_ALL='en_US.UTF-8'

# Highlight section titles in manual pages.
# Colors for less
# ------ ANSI codes ------
# Black            \e[0;30m
# Blue             \e[0;34m
# Green            \e[0;32m
# Cyan             \e[0;36m
# Red              \e[0;31m
# Purple           \e[0;35m
# Brown            \e[0;33m
# Gray             \e[0;37m
# Dark Gray        \e[1;30m
# Light Blue       \e[1;34m
# Light Green      \e[1;32m
# Light Cyan       \e[1;36m
# Light Red        \e[1;31m
# Light Purple     \e[1;35m
# Yellow           \e[1;33m
# White            \e[1;37m
export LESS_TERMCAP_mb=$'\e[1;31m'     # begin bold
export LESS_TERMCAP_md=$'\e[1;36m'     # begin blink
export LESS_TERMCAP_me=$'\e[0m'        # reset bold/blink
export LESS_TERMCAP_so=$'\e[01;33m'    # begin reverse video
export LESS_TERMCAP_se=$'\e[0m'        # reset reverse video
export LESS_TERMCAP_us=$'\e[1;32m'     # begin underline
export LESS_TERMCAP_ue=$'\e[0m'        # reset underline

# LESS defaults
# X - leave content on-screen
# F - quit automatically if less than one screenfull
# R - raw terminal characters
# i - ignore case in search pattern. This option is ignored if it contains
#     uppercase characters
# J - Show status column at the left edge of the screen
export LESS='-X -F -R -i -J -W --tabs=4 --window=4'

# Make Python use UTF-8 encoding for output to stdin, stdout, and stderr.
export PYTHONIOENCODING='UTF-8'

# Avoid issues with `gpg` as installed via Homebrew.
# https://stackoverflow.com/a/42265848/96656
TTY=$(tty)
export GPG_TTY=$TTY
unset TTY

# Opt-out of homebrew's analytics
export HOMEBREW_NO_ANALYTICS=1
# Do not create the lock file on `brew bundle`
export HOMEBREW_BUNDLE_NO_LOCK=1
export HOMEBREW_BUNDLE_FILE="${HOME}/dotfiles/lib/Brewfile"

# nnn options
# -d : detail mode
# -D : show directories in context color with NNN_FCOLORS set
# -e : open text files in $VISUAL (else $EDITOR, fallback vi) [preferably CLI]
# -E : use $EDITOR for internal undetached edits
# -H : show hidden files (toggled with '.')
# -u : use selection if available, don't prompt to choose between selection and hovered entry
# -U : show user and group names in status bar
export NNN_OPTS="dDeHuU"
export NNN_FIFO=/tmp/nnn.fifo
# export NNN_TRASH=1

# nnn plugins
# - To run a plugin, press ; followed by the key or Alt+key
# - To skip directory refresh after running a plugin, prefix with -
# - To assign keys to arbitrary non-background non-shell-interpreted cli
#   commands and invoke like plugins, add _ (underscore) before the command.
#
# shellcheck disable=SC2016 # (we don't want expansion for $nnn)
NNN_SHELL_PLUGINS='l:-_git log;x:_chmod +x $nnn'
NNN_PLUGINS='p:preview-tui-ext;c:fzcd;o:fzopen'
export NNN_PLUG="$NNN_PLUGINS;$NNN_SHELL_PLUGINS"
unset NNN_SHELL_PLUGINS NNN_PLUGINS

# Fzf configuration
export FZF_DEFAULT_COMMAND='fd --type f --hidden --exclude .git'
export FZF_DEFAULT_OPTS='
  --height=50%
  --layout=reverse
  --info=inline
  --prompt="❯ "
  --bind=ctrl-p:toggle-preview
  --color fg:#ebdbb2,bg:#282828,hl:#fabd2f,fg+:#ebdbb2,bg+:#3c3836,hl+:#fabd2f
  --color info:#83a598,prompt:#bdae93,spinner:#fabd2f,pointer:#83a598,marker:#fe8019,header:#665c54
'
# Molokai for fzf
# --color fg:252,bg:233,hl:67,fg+:252,bg+:235,hl+:81
# --color info:144,prompt:161,spinner:135,pointer:135,marker:118

export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_CTRL_T_OPTS='--preview "bat --color=always --line-range :300 {}"'

# Alt-c on Mac is <Esc c> which is pressing c after pressing the escape key
# You can change it in settings > profile > keys > option > Esc+
# I prefer not to change it as my Capslock is Control and escape
export FZF_ALT_C_COMMAND='fd --type d . --hidden --exclude .git'
export FZF_ALT_C_OPTS='--preview "tree -C {} | head -100"'

# From Homebrew:
# ruby-build installs a non-Homebrew OpenSSL for each Ruby version installed
# and these are never upgraded.
#
# Note: this may interfere with building old versions of Ruby (e.g <2.4) that use
# OpenSSL <1.1.
openssl_path=$(brew --prefix openssl@1.1)
export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$openssl_path"
unset openssl_path
