#!/usr/bin/env bash
# vim: set ft=sh:

# Disale default conda base getting activated by default
export CONDA_AUTO_ACTIVATE_BASE=false;

# Hide the “default interactive shell is now zsh” warning on macOS.
export BASH_SILENCE_DEPRECATION_WARNING=1;

# Make vim the default editor.
export EDITOR='vim';

# Increase Bash history size. Allow 32³ entries; the default is 500.
export HISTSIZE='32768';
export HISTFILESIZE="${HISTSIZE}";
# Omit duplicates and commands that begin with a space from history.
export HISTCONTROL='ignoreboth';

# Prefer US English and use UTF-8.
export LANG='en_US.UTF-8';
export LC_ALL='en_US.UTF-8';

# Fixing the italics in vim
# Still need to fix it in tmux
export TERM=xterm-256color

# LESS defaults
# X - leave content on-screen
# F - quit automatically if less than one screenfull
# R - raw terminal characters
# i - ignore case in search pattern
export LESS='-X -F -R -i -J -W --tabs=4 --window=4';

# Make Python use UTF-8 encoding for output to stdin, stdout, and stderr.
export PYTHONIOENCODING='UTF-8';

# Avoid issues with `gpg` as installed via Homebrew.
# https://stackoverflow.com/a/42265848/96656
TTY=$(tty)
export GPG_TTY=$TTY
unset TTY

# Opt-out of homebrew's analytics
export HOMEBREW_NO_ANALYTICS=1

# Do not create the lock file on `brew bundle`
export HOMEBREW_BUNDLE_NO_LOCK=1
