#!/usr/bin/env bash

# Create a new directory and enter it
function mcd() {
	mkdir -p "$@" && cd "$_" || return;
}

# Normalize `open` across Linux, macOS, and Windows.
# This is needed to make the `o` function (see below) cross-platform.
if [ ! "$(uname -s)" = 'Darwin' ]; then
	if grep -q Microsoft /proc/version; then
		# Ubuntu on Windows using the Linux subsystem
		alias open='explorer.exe';
	else
		alias open='xdg-open';
	fi
fi

# `o` with no arguments opens the current directory, otherwise opens the given
# location
function o() {
	if [ $# -eq 0 ]; then
		open .;
	else
		open "$@";
	fi;
}

# To open the python source folder directly using pyc in vscode :)
function pyc() {
	path=$(python -c "import os;print(os.__file__.split('os.py')[0])")
	code "$path"
}

# https://snarky.ca/why-you-should-use-python-m-pip/
# Let's convert `pip` to `python -m pip` and add some other functionality to it
function pip() {
	if [ "$1" != "freeze" ]; then
		echo "Current Python interpreter: $(python -V)"
		echo -e "$(python -m pip -V)\n"
	fi
	python -m pip "$@"
}
