#!/usr/bin/env bash

# No bell please
set bell-style none

# Briefly move the cursor to an opening parenthesis when a closing parenthesis
# is inserted.
set blink-matching-paren on

# Disable Bash 5.1 highlighted paste feature.
set enable-bracketed-paste off

# Color the common prefix in the completion list
set colored-completion-prefix on

# Make Tab autocomplete regardless of filename case
set completion-ignore-case on

# List all matches in case multiple possible completions are possible
set show-all-if-ambiguous on

# Immediately add a trailing slash when autocompleting symlinks to directories
set mark-symlinked-directories on

# Enabling basic vim emulation
set editing-mode vi
set keymap vi-insert

# Show vim mode in the prompt
set show-mode-in-prompt on
set vi-cmd-mode-string "\1\e[1;37m\2: \1\e[0m\2"
set vi-ins-mode-string "\1\e[1;37m\2+ \1\e[0m\2"

# Do not autocomplete hidden files unless the pattern explicitly begins with a dot
set match-hidden-files off

# Show all autocomplete results at once
set page-completions off

# If there are more than 200 possible completions for a word, ask to show them all
set completion-query-items 200

# Show extra file information when completing, like `ls -F` does
set visible-stats on

# Be more intelligent when autocompleting by also looking at the text after
# the cursor. For example, when the current line is "cd ~/src/mozil", and
# the cursor is on the "z", pressing Tab will not autocomplete it to "cd
# ~/src/mozillail", but to "cd ~/src/mozilla". (This is supported by the
# Readline used by Bash 4.)
set skip-completed-text on

# Allow UTF-8 input and output, instead of showing stuff like $'\0123\0456'
set input-meta on
set output-meta on
set convert-meta off

# NOTE: All keybindings should come at the end of the file
# Use the text that has already been typed as the prefix for searching through
# commands (i.e. more intelligent Up/Down behavior)
"\C-j": history-search-forward
"\C-k": history-search-backward
"\C-l": clear-screen

# Make Tab cycle between possible completions
# Cycle forward: Tab
# Cycle backward: Shift-Tab
TAB: menu-complete
"\e[Z": menu-complete-backward

# "\C-a": beginning-of-line  # used as tmux prefix
"\C-e": end-of-line
