#!/usr/bin/env bash

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob

# Append to the Bash history file, rather than overwriting it
shopt -s histappend

# Autocorrect typos in path names when using `cd`
shopt -s cdspell

# * `autocd`, e.g. `**/qux` will enter `./foo/bar/baz/qux`
shopt -s autocd

# * Recursive globbing, e.g. `echo **/*.txt`
shopt -s globstar
