#!/usr/bin/env bash

# Start PATH from here (default path in MacOS)
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

# Setting PATH for useful scripts
export PATH="${PATH}:${HOME}/dotfiles/bin"

# Setting PATH for private scripts
export PATH="${PATH}:${HOME}/projects/bin"
