#!/usr/bin/env bash

# Start PATH from here (default path in MacOS)
PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

# Setting PATH for useful scripts
PATH="${PATH}:${HOME}/dotfiles/bin"

# Setting PATH for private scripts
PATH="${PATH}:${HOME}/projects/bin"

# Setting PATH for smlnj
PATH="${PATH}:/usr/local/smlnj/bin"

# Setting PATH for pipx
PATH="${PATH}:${HOME}/.local/bin"

# Setting PATH for tcl-tk
PATH="/usr/local/opt/tcl-tk/bin:${PATH}"

export PATH
