#!/usr/bin/env bash

# FIXME: find a better way to do PATH management
# Start PATH from here (default path in MacOS)
PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

# Setting PATH for useful scripts
PATH="${PATH}:${HOME}/dotfiles/bin"

# Setting PATH for private scripts
PATH="${PATH}:${HOME}/projects/bin"

# Setting PATH for smlnj
PATH="${PATH}:/usr/local/smlnj/bin"

# Setting PATH for pipx
PATH="${PATH}:${HOME}/.local/bin"

# Setting PATH for tcl-tk
PATH="/usr/local/opt/tcl-tk/bin:${PATH}"

# Setting PATH for go
export GOPATH="${HOME}/go"
PATH="${PATH}:${GOPATH}/bin"

# Setting PATH for rust
# export RUSTUP_HOME="${HOME}/.rustup"
export CARGO_HOME="${HOME}/.cargo"
PATH="${PATH}:${CARGO_HOME}/bin"

# Setting PATH for BasicTex
PATH="/Library/TeX/texbin:${PATH}"

# Neovim nightly
PATH="${HOME}/neovim/bin:${PATH}"

export PATH
