# style name or JSON path (default "auto")
style: "~/dotfiles/config/glow/style/gruvbox_dark.json"
# show local files only; no network (TUI-mode only)
local: false
# mouse support (TUI-mode only)
mouse: false
# use pager to display markdown
pager: true
# word-wrap at width
width: 80
