# This group of options represents a command-line flag/option.  Flags explicitly
# added when running (ie: btm -a) will override this config file if an option
# is also set here.

[flags]

# The update rate of the application.
rate = 1500

# Whether to group processes with the same name together by default.
# Press <Tab> to toggle between them.
group_processes = false

# Whether to make process searching case sensitive by default.
case_sensitive = false

# Whether to make process searching use regex by default.
regex = true

# The default time interval (in milliseconds).
default_time_value = 300000

# Override layout default widget
default_widget_type = "proc"

# Remove space in tables
hide_table_gap = true

# Built-in themes.
# Available: "default", "gruvbox", "nord" (and their *-light counterparts)
color = "gruvbox"

# Show memory values in the processes widget as values by default.
mem_as_value = true

# Shows the list scroll position tracker in the widget title for table widgets.
# Eg., Processes (1 of 527)
show_table_scroll_position = true

# Displays the network widget using bytes. Defaults to bits.
network_use_bytes = true

# Layout - layouts follow a pattern like this:
# [[row]] represents a row in the application.
# [[row.child]] represents either a widget or a column.
# [[row.child.child]] represents a widget.
#
# All widgets must have the type value set to one of:
# ["cpu", "mem", "proc", "net", "temp", "disk", "empty"].
#
# All layout components have a ratio value - if this is not set, then it defaults to 1.

[[row]]
  ratio=3
  [[row.child]]
    type="cpu"
[[row]]
  ratio=7
  [[row.child]]
    ratio=7
    [[row.child.child]]
      type="proc"
  [[row.child]]
    ratio=3
    [[row.child.child]]
      ratio=4
      type="mem"
    [[row.child.child]]
      ratio=4
      type="net"
    [[row.child.child]]
      ratio=2
      type="batt"
