#!/usr/bin/env bash
# shellcheck disable=SC1090,SC1091
# Bash completions
BREW_PREFIX="$(brew --prefix)"
FZF_COMPLETION_PATH="/usr/local/opt/fzf/shell/completion.bash"

# Add tab completion for many Bash commands
if which brew &> /dev/null && [[ -r "${BREW_PREFIX}/etc/profile.d/bash_completion.sh" ]]; then
  # Ensure existing Homebrew v1 completions continue to work
  export BASH_COMPLETION_COMPAT_DIR="${BREW_PREFIX}/etc/bash_completion.d";
  source "${BREW_PREFIX}/etc/profile.d/bash_completion.sh";
elif [[ -f "/etc/bash_completion" ]]; then
  source "/etc/bash_completion";
fi;

# Tab completions for aliases
___git_complete g __git_main
complete -o default -o nospace -F _docker_compose dc

# Fzf auto-complete
if [[ -r "${FZF_COMPLETION_PATH}" ]]; then
  source "${FZF_COMPLETION_PATH}"
fi

unset BREW_PREFIX FZF_COMPLETION_PATH
