on: [push, pull_request]

name: "build"

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Run bootstrap
        run: |
          set -eo pipefail
          export TERM=xterm
          export CI=1
          curl -o bootstrap.sh https://raw.githubusercontent.com/dhruvmanila/dotfiles/master/bootstrap
          printf 'yy' | sudo bash bootstrap.sh
        shell: bash


