on: [push, pull_request]

name: "build"

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Run bootstrap
        run: |
          set -exo pipefail
          export TERM=xterm
          export CI=1
          curl -o bootstrap.sh https://raw.githubusercontent.com/dhruvmanila/dotfiles/master/bootstrap
          echo -e "y\ny\n" > response.txt
          cat response.txt
          bash bootstrap.sh < response.txt
          printf 'y\ny\n' | bash bootstrap.sh
          printf 'yy' | bash bootstrap.sh
          yes | bash bootstrap.sh
        shell: bash 
