on: [push, pull_request]

name: "build"

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Run bootstrap
        run: |
          set -eo pipefail
          export TERM=xterm
          export CI=1
          curl -o bootstrap.sh https://raw.githubusercontent.com/dhruvmanila/dotfiles/master/bootstrap
          printf 'yn' | bash bootstrap.sh
        shell: bash
  osxdefaults:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Run osxdefaults
        run: sudo bash lib/osxdefaults
        shell: bash
