on: [push, pull_request]

name: 'Shellcheck'

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@0.5.0
        env:
          SHELLCHECK_OPTS: -e SC2059 -e SC1090 -e SC1091

